# Path to your oh-my-zsh configuration.
ZSH=$HOME/dotfiles/zsh/oh-my-zsh
ZSH_CUSTOM=$HOME/dotfiles/zsh/custom

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="dangerous"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(bundler git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
setopt rmstarsilent
setopt nohistverify

export EDITOR=vim
zstyle ':completion:*' matcher-list ''

alias pushdep='cd && sudo rsync -av --exclude=deployment-scripts/modules ~deploy/deployment-scripts . && sudo chown -R david deployment-scripts && cd deployment-scripts && git push'

alias ss='sudo su -'

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

unalias run-help 2>/dev/null
autoload run-help
HELPDIR=/usr/local/share/zsh/help
alias x='exit'

source /usr/local/share/zsh/site-functions/_aws

staging() { heroku "$@" --remote staging }
# don't want to run this by mistake, ever!
#production() { heroku "$@" --remote production }

if test -f ~/.gnupg/.gpg-agent-info -a -n "$(pgrep gpg-agent)"; then
  source ~/.gnupg/.gpg-agent-info
  export GPG_AGENT_INFO
else
  eval $(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)
fi
